"""Equipment rows: power, usage, ownership. A blank outlet means "nearest socket"."""
from example_helpers import E

AG, PG, IG, FAC = "Characterisation group", "Fabrication group", "Imaging group", "Facility"
EX = "ExampleCo"

EQUIPMENT = [
    # --- LAB-A ---
    E("SPEC-01", EX, "UV-1000", AG, "working", "keep", "weekly", "booking", "optical", 1, "standard", 150, 300,
      serial="SN0012345", asset_tag="000456789", critical="no", weight=25),
    E("SPEC-02", EX, "UV-500", AG, "broken", "dispose", "never", "estimate", "optical", 1, "standard", None, None,
      asset_tag="000123001", weight=30, notes="removing it frees 0.35 m2 of bench"),
    E("UVO-01", EX, "UVO-42", PG, "working", "keep", "daily", "tally", "cleaning", 1, "standard", 350, 1000,
      asset_tag="000456790", critical="no", weight=30, manual="manuals/UVO-01.pdf"),
    E("BAL-01", EX, "Bal-220", PG, "working", "keep", "daily", "tally", "solution-prep", 1, "standard", 10, 20,
      critical="no", weight=8),
    E("VORT-01", EX, "Vortex", PG, "working", "keep", "daily", "estimate", "solution-prep", 1, "standard", 30, 60,
      critical="no", weight=2),
    E("VAC-01", EX, "RV-5", PG, "working", "keep", "weekly", "estimate", "drying", 1, "standard", 370, 900,
      critical="no", weight=20),
    E("FRZ-01", EX, "CF-300", FAC, "working", "keep", "daily", "estimate", "storage", 1, "standard", 800, 1600,
      critical="yes", weight=300, outlet="OUT-03", notes="on its own circuit"),
    E("FRZ-02", EX, "UC-20", PG, "working", "keep", "daily", "estimate", "storage", 1, "standard", 150, 400,
      critical="yes", weight=45, notes="EXAMPLE PROBLEM: shares circuit DB2-C07 with UVO-01"),
    E("FRG-01", EX, "UC-4", PG, "working", "relocate", "daily", "estimate", "storage", 1, "standard", 100, 300,
      critical="no", weight=35),
    E("HOOD-01", None, None, FAC, "working", "keep", "daily", "estimate", "solution-prep", 0, "hardwired", None, None,
      critical="no", notes="fan runs on the building exhaust"),
    E("HP-01", EX, "HS-600", PG, "working", "keep", "daily", "estimate", "solution-prep", 1, "standard", 600, 800,
      critical="no", weight=5, outlet="OUT-05"),
    E("HP-02", EX, "HS-600", PG, "working", "keep", "weekly", "estimate", "solution-prep", 1, "standard", 600, 800,
      critical="no", weight=5, outlet="OUT-05"),
    E("FURN-01", EX, "TF-1200", PG, "working", "keep", "weekly", "booking", "annealing", 1, "standard", 2000,
      2400, critical="no", weight=45, outlet="OUT-06",
      notes="EXAMPLE PROBLEM: with the hotplates and the bath it overloads DB2-C10"),
    E("BATH-01", EX, "US-10H", PG, "working", "keep", "weekly", "estimate", "cleaning", 1, "standard", 800, 1000,
      critical="no", weight=12, outlet="OUT-06"),
    E("HYG-01", EX, "RH-Log", PG, "working", "keep", "daily", "tally", "solution-prep", 1, "standard", 5, 10,
      critical="no", weight=2),
    E("PC-01", EX, "Tower", AG, "working", "keep", "daily", "estimate", "optical", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-01"),
    E("MON-01", EX, "24in", AG, "working", "keep", "daily", "estimate", "optical", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-01"),
    E("MIC-01", EX, "Scope-M", IG, "working", "keep", "weekly", "booking", "inspection", 1, "standard", 60, 100,
      critical="no", weight=12, outlet="STRIP-05"),
    E("LAP-02", EX, "Laptop", IG, "working", "keep", "weekly", "estimate", "inspection", 1, "standard", 50, 90,
      critical="no", outlet="STRIP-05"),
    E("SMU-01", EX, "SMU-2400", "Electronics group", "working", "keep", "weekly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("SMU-02", EX, "SMU-2400", "Electronics group", "working", "keep", "weekly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("SMU-03", EX, "SMU-2400", "Electronics group", "working", "keep", "monthly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("OVEN-02", EX, "VO-50", PG, None, "new", "daily", "estimate", "drying", 1, "standard", 250, 500,
      critical="no", weight=60, notes="arriving: needs a spot"),
    # --- LAB-B ---
    E("PRB-01", EX, "PS-4", AG, "working", "keep", "daily", "booking", "device-testing", 1, "standard", 400, 600,
      critical="no", weight=60, outlet="STRIP-02"),
    E("SUN-01", EX, "SS-150X", AG, "working", "keep", "daily", "booking", "device-testing", 1, "standard", 1500,
      2000, critical="no", weight=110, outlet="STRIP-02", notes="the xenon lamp makes ozone: needs extraction"),
    E("VAC-02", EX, "SC-15", AG, "working", "keep", "daily", "estimate", "device-testing", 1, "standard", 400, 800,
      critical="no", weight=30, outlet="STRIP-02"),
    E("PC-02", EX, "Tower", AG, "working", "keep", "daily", "estimate", "device-testing", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-02"),
    E("MON-02", EX, "24in", AG, "working", "keep", "daily", "estimate", "device-testing", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-02"),
    E("LAS-01", EX, "DL-405", AG, "working", "keep", "weekly", "estimate", "photoluminescence", 1, "standard", 300, 500,
      critical="no", weight=15),
    E("COR-01", EX, "CC-30", AG, "working", "keep", "weekly", "estimate", "device-testing", 1, "standard", 100, 150,
      critical="no", weight=6, outlet="STRIP-03"),
    E("PRN-01", EX, "Inkjet", AG, "working", "keep", "weekly", "estimate", None, 1, "standard", 30, 60,
      critical="no", outlet="STRIP-03"),
    E("SRV-01", EX, "Server", AG, "working", "keep", "daily", "estimate", None, 1, "standard", 200, 400,
      critical="no", weight=15, outlet="OUT-10"),
    E("N2G-01", EX, "Gen-N2", AG, "working", "keep", "daily", "estimate", "glovebox", 1, "standard", 600, 1200,
      critical="no", weight=70, outlet="OUT-10"),
    E("CRYO-01", EX, "CC-4K", AG, "working", "keep", "weekly", "booking", "low-temperature", 1, "standard", 800, 2000,
      critical="no", weight=50, outlet="OUT-11"),
    E("PC-03", EX, "Tower", AG, "working", "keep", "weekly", "estimate", "low-temperature", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-04"),
    E("MON-03", EX, "24in", AG, "working", "keep", "weekly", "estimate", "low-temperature", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-04"),
    E("FTIR-01", EX, "IR-4", AG, "faulty", "undecided", "monthly", "booking", None, 1, "standard", 150, 250,
      critical="no", weight=35, outlet="OUT-11", notes="faulty: repair or replace?"),
    E("LAP-01", EX, "Laptop", AG, "working", "keep", "monthly", "estimate", None, 1, "standard", 50, 90,
      critical="no", outlet="STRIP-04"),
    E("LABEL-01", EX, "Label-P", AG, "working", "keep", "daily", "estimate", None, 1, "standard", 20, 40,
      critical="no"),
    E("LED-01", EX, "LED-1S", AG, "working", "keep", "daily", "tally", "device-testing", 1, "standard", 200, 400,
      critical="no", weight=6),
    E("VORT-02", EX, "Vortex", AG, "working", "keep", "daily", "estimate", "sample-prep", 1, "standard", 30, 60,
      critical="no", weight=2),
    E("DARK-01", EX, "DB-2", AG, "working", "keep", "daily", "tally", "device-testing", 1, "standard", 10, 20,
      critical="no", weight=8),
]
