"""Items: the long tail that lives in drawers, shelves and boxes."""

_ROWS = [
    # name | synonyms | container | qty | category | notes
    ("Hex key set 1.5-10 mm", "allen key; hex wrench; inbus", "PED-01.D2", 1, "tool", None),
    ("Screwdriver set", "screwdrivers; phillips; flathead; slotted", "PED-01.D2", 1, "tool", None),
    ("Parafilm", "sealing film; lab film; wax film", "PED-01.D1", "3 rolls", "consumable", None),
    ("Spare fuses, 10 A", "fuse; fuses", "BENCH-02.D1", 5, "spare-part", "for UVO-01, see its SOP"),
    ("USB A-B cables, 3 m", "printer cable; usb-b", "BOX-01", 4, "cable", None),
    ("UV lamp for the UV-ozone cleaner (spare)", "uv lamp; ozone lamp; low-pressure mercury lamp", "CAB-01.S2", 1,
     "spare-part", None),
    ("Nitrile gloves, size M", "gloves", "CAB-01.S1", "10 boxes", "consumable", None),
    ("Instrument manuals", "manual; binders; documentation", "CAB-01.S1", None, "documentation", None),
    ("Pipette tips 200 µL", "tips; yellow tips", "PED-01.D1", "5 racks", "consumable", None),
    ("Pipette tips 1000 µL", "tips; blue tips", "PED-01.D1", "5 racks", "consumable", None),
    ("Weighing boats", "weigh boats; weighing dishes", "BENCH-02.D2", "1 box", "consumable", None),
    ("Spatulas", "spatula; scoop", "BENCH-02.D2", 6, "tool", None),
    ("Balance calibration weights", "calibration weight; test weights; check weights", "BENCH-02.D1", "1 set",
     "tool", "for BAL-01"),
    ("Desiccant packs", "silica gel; desiccant", "CAB-01.S2", "3 bags", "consumable", "for the substrate boxes"),
    ("Magnetic stir bars", "stirrer bars; flea; stir fleas", "PED-01.D3", "~30", "consumable", None),
    ("Stir bar retriever", "magnet wand; flea catcher", "PED-01.D3", 1, "tool", None),
    ("Quartz boats", "boats; combustion boats; crucibles", "PED-01.D1", 4, "consumable", "for FURN-01"),
    ("Heat-resistant gloves", "oven gloves; furnace gloves; thermal gloves", "CAB-01.S1", "2 pairs", "tool", None),
    ("Glass substrates 25 × 25 mm", "glass slides; substrates; soda-lime glass", "CAB-01.S2", "2 boxes", "substrate",
     None),
    ("ITO substrates 25 × 25 mm", "ito; ito glass; indium tin oxide; substrates", "CAB-01.S2", "3 boxes", "substrate",
     None),
    ("Lens paper", "lens tissue", "PED-01.D3", "2 packs", "consumable", "for MIC-01"),
    ("Cable ties", "zip ties; tie wraps", "BOX-01", "1 bag", "consumable", None),
    ("Electrical tape", "insulating tape; pvc tape", "BOX-01", 2, "consumable", None),
    ("Multimeter", "voltmeter; dmm", "BOX-01", 1, "tool", None),
    ("Vacuum pump oil", "pump oil", "BENCH-02.D2", "1 L", "spare-part", "for VAC-01"),
    ("Sample storage boxes", "membrane boxes; wafer boxes; sample boxes", "PED-02.D1", "3 boxes", "consumable", None),
    ("Kapton tape", "polyimide tape; kapton", "PED-02.D1", 4, "consumable", None),
    ("Silver paste", "conductive paste; silver epoxy; contact paste", "PED-02.D2", 2, "consumable", None),
    ("Indium wire", "indium; contact wire", "PED-02.D2", "1 spool", "consumable", None),
    ("Xenon lamp 150 W (spare)", "arc lamp; xe lamp; solar simulator lamp", "CAB-02.S1", 1, "spare-part", None),
    ("Probe tips, tungsten", "probe needles; tips; tungsten tips", "CAB-02.S1", 5, "spare-part", None),
    ("Reference solar cell (calibrated)", "reference cell; calibration cell; si reference", "CAB-02.S2", 1, "tool",
     "for SUN-01: irradiance calibration"),
    ("BNC to triax adapters", "triax; bnc; adapters", "BOX-02", 4, "electronics", None),
    ("BNC coax cables", "bnc cables; coaxial cables; coax", "BOX-02", "1 bag", "cable", None),
    ("Cryogenic grease", "apiezon; vacuum grease; n grease; thermal grease", "BOX-04", 2, "consumable",
     "for CRYO-01"),
    ("Cold-head O-rings", "o-rings; seals; o ring", "BOX-04", 10, "spare-part", None),
    ("Cryostat window, quartz (spare)", "optical window; quartz window", "CAB-02.S3", 1, "spare-part", None),
    ("Indium foil", "indium; thermal contact foil", "BOX-04", 20, "spare-part", None),
    ("Gas leak detector", "leak detector; leak checker", "PED-03.D1", 1, "tool", None),
    ("Tweezers", "forceps", "PED-03.D1", 3, "tool", None),
    ("ATR cleaning wipes", "lens wipes; kimwipes; tissues", "PED-03.D2", "2 boxes", "consumable", "for FTIR-01"),
    ("Neutral density filters", "nd filters; attenuators; filters", "BOX-03", "1 set", "optics", None),
    ("Shadow masks, 0.1 cm² cells", "masks; aperture masks; evaporation masks", "PED-03.D2", "2 sets", "tool", None),
    ("Substrate racks (PTFE)", "racks; cleaning racks; teflon racks", "PED-03.D3", 6, "tool", None),
    ("Label printer tape", "labels; label cassette", "PED-02.D3", 3, "consumable", "for LABEL-01"),
    ("Printer paper", "paper; a4", "CAB-02.S3", "2 reams", "consumable", None),
    ("Spare network cables", "ethernet cable; patch cable; lan cable", "PED-02.D3", 5, "cable", None),
    ("USB drives", "usb stick; memory stick; flash drive", "PED-03.D1", 3, "other", None),
    ("Wrench set", "spanners; open-end wrench", "PED-02.D3", 1, "tool", None),
    ("Nitrogen generator filters (spare)", "n2 filter; generator filter", "CAB-02.S3", 2, "spare-part",
     "for N2G-01"),
    ("Oven door seal", "gasket; door gasket", "CAB-01.S2", 1, "spare-part", None),
]

from datetime import date

DOCUMENTS = [
    dict(id="COSHH-014", type="coshh", title="Immersion oil and lens-cleaning solvents", applies_to="MIC-01",
         status="approved", filled=date(2026, 3, 2), expires=date(2029, 3, 2), approved_by="Safety officer",
         link="https://intranet.example.org/coshh/COSHH-014.pdf", notes="EXAMPLE"),
    dict(id="RA-003", type="risk-assessment", title="Tube furnace operation", applies_to="FURN-01",
         status="approved", filled=date(2025, 11, 10), expires=date(2028, 11, 10), approved_by="Safety officer",
         link="S:/Safety/RA-003.pdf", notes="EXAMPLE"),
    dict(id="CAL-021", type="calibration", title="Balance and solar simulator irradiance calibration",
         applies_to="BAL-01; SUN-01",
         status="approved", filled=date(2026, 6, 1), expires=date(2029, 6, 1), link="S:/Calibration/CAL-021.pdf",
         notes="EXAMPLE"),
    dict(id="PAT-2026-A", type="electrical-test", title="PAT tests, fabrication lab", applies_to="LAB-A", status="approved",
         filled=date(2026, 1, 15), expires=date(2029, 1, 15), notes="EXAMPLE"),
    dict(id="RA-022", type="risk-assessment", title="Optical radiation: solar simulator and laser",
         applies_to="SUN-01; LAS-01",
         status="pending", filled=date(2026, 9, 1), notes="EXAMPLE WARNING: not approved yet"),
]

# Ordering details and spare-part tracking, by item name. notes=None clears a "for X" note that spare_for replaces.
_MORE = {
    "Spare fuses, 10 A": dict(spare_for="UVO-01", min_qty=2, rs_part="000-0101", notes="EXAMPLE part number"),
    "UV lamp for the UV-ozone cleaner (spare)": dict(spare_for="UVO-01", min_qty=1),
    "Vacuum pump oil": dict(spare_for="VAC-01", min_qty=1, rs_part="000-0102", notes="EXAMPLE part number"),
    "Xenon lamp 150 W (spare)": dict(spare_for="SUN-01", min_qty=1,
                                     buy_link="https://www.example.com/lamps/xenon-150"),
    "Probe tips, tungsten": dict(qty=2, spare_for="PRB-01", min_qty=4,
                                 notes="EXAMPLE WARNING: 2 left, keep at least 4"),
    "BNC to triax adapters": dict(spare_for="PRB-01"),
    "BNC coax cables": dict(spare_for="PRB-01; SUN-01"),
    "Cold-head O-rings": dict(qty=0, spare_for="CRYO-01", min_qty=5, rs_part="000-0103",
                              notes="EXAMPLE WARNING: none left"),
    "Cryostat window, quartz (spare)": dict(spare_for="CRYO-01", min_qty=1),
    "Indium foil": dict(spare_for="CRYO-01", min_qty=10),
    "Nitrogen generator filters (spare)": dict(container=None, elsewhere="Main stores, building 2, cage 3",
                                               spare_for="N2G-01", min_qty=1, notes="kept outside the lab",
                                               buy_link="https://www.example.com/n2-generator/filter-kit"),
    "Multimeter": dict(rs_part="000-0104", notes="EXAMPLE part number"),
    "Cable ties": dict(rs_part="000-0105", notes="EXAMPLE part number"),
    "Nitrile gloves, size M": dict(buy_link="https://www.example.com/gloves/nitrile-m"),
    "Oven door seal": dict(spare_for="OVEN-01", notes="EXAMPLE WARNING: a spare for an oven that's gone"),
}
ITEMS = []
for n, (name, syn, cont, qty, cat, notes) in enumerate(_ROWS, 1):
    row = dict(id=f"I-{n:04d}", name=name, synonyms=syn, container=cont, qty=qty, category=cat, notes=notes)
    row.update(_MORE.get(name, {}))
    ITEMS.append(row)
assert len(ITEMS) == len({r["name"] for r in ITEMS}) and set(_MORE) <= {r["name"] for r in ITEMS}
