"""Equipment rows: power, usage, ownership. A blank outlet means "nearest socket"."""
from example_helpers import E

AG, PG, IG, FAC = "Analytics group", "Prep group", "Imaging group", "Facility"
EX = "ExampleCo"

EQUIPMENT = [
    # --- LAB-A ---
    E("SPEC-01", EX, "UV-1000", AG, "working", "keep", "weekly", "booking", "analysis", 1, "standard", 150, 300,
      serial="SN0012345", asset_tag="000456789", critical="no", weight=25),
    E("SPEC-02", EX, "UV-500", AG, "broken", "dispose", "never", "estimate", "analysis", 1, "standard", None, None,
      asset_tag="000123001", weight=30, notes="removing it frees 0.35 m2 of bench"),
    E("CEN-01", EX, "Spin-5", PG, "working", "keep", "daily", "tally", "sample-prep", 1, "standard", 350, 1000,
      asset_tag="000456790", critical="no", weight=30, manual="manuals/CEN-01.pdf"),
    E("BAL-01", EX, "Bal-220", PG, "working", "keep", "daily", "tally", "sample-prep", 1, "standard", 10, 20,
      critical="no", weight=8),
    E("VORT-01", EX, "Vortex", PG, "working", "keep", "daily", "estimate", "sample-prep", 1, "standard", 30, 60,
      critical="no", weight=2),
    E("PUMP-01", EX, "Vac-2", PG, "working", "keep", "weekly", "estimate", "sample-prep", 1, "standard", 370, 900,
      critical="no", weight=20),
    E("FRZ-01", EX, "ULT-500", FAC, "working", "keep", "daily", "estimate", "storage", 1, "standard", 800, 1600,
      critical="yes", weight=300, outlet="OUT-03", notes="on its own circuit"),
    E("FRZ-02", EX, "UC-20", PG, "working", "keep", "daily", "estimate", "storage", 1, "standard", 150, 400,
      critical="yes", weight=45, notes="EXAMPLE PROBLEM: shares circuit DB2-C07 with CEN-01"),
    E("FRG-01", EX, "UC-4", PG, "working", "relocate", "daily", "estimate", "storage", 1, "standard", 100, 300,
      critical="no", weight=35),
    E("HOOD-01", None, None, FAC, "working", "keep", "daily", "estimate", "synthesis", 0, "hardwired", None, None,
      critical="no", notes="fan runs on the building exhaust"),
    E("HP-01", EX, "Stir-600", PG, "working", "keep", "daily", "estimate", "synthesis", 1, "standard", 600, 800,
      critical="no", weight=5, outlet="OUT-05"),
    E("HP-02", EX, "Stir-600", PG, "working", "keep", "weekly", "estimate", "synthesis", 1, "standard", 600, 800,
      critical="no", weight=5, outlet="OUT-05"),
    E("AUTO-01", EX, "Clave-20", PG, "working", "keep", "weekly", "booking", "sterilisation", 1, "standard", 2000,
      2400, critical="no", weight=45, outlet="OUT-06",
      notes="EXAMPLE PROBLEM: with the hotplates and water bath it overloads DB2-C10"),
    E("WB-01", EX, "Bath-10", PG, "working", "keep", "weekly", "estimate", "sample-prep", 1, "standard", 800, 1000,
      critical="no", weight=12, outlet="OUT-06"),
    E("PH-01", EX, "pH-7", PG, "working", "keep", "daily", "tally", "sample-prep", 1, "standard", 5, 10,
      critical="no", weight=2),
    E("PC-01", EX, "Tower", AG, "working", "keep", "daily", "estimate", "analysis", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-01"),
    E("MON-01", EX, "24in", AG, "working", "keep", "daily", "estimate", "analysis", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-01"),
    E("MIC-01", EX, "Scope-M", IG, "working", "keep", "weekly", "booking", "imaging", 1, "standard", 60, 100,
      critical="no", weight=12, outlet="STRIP-05"),
    E("LAP-02", EX, "Laptop", IG, "working", "keep", "weekly", "estimate", "imaging", 1, "standard", 50, 90,
      critical="no", outlet="STRIP-05"),
    E("SMU-01", EX, "SMU-2400", "Electronics group", "working", "keep", "weekly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("SMU-02", EX, "SMU-2400", "Electronics group", "working", "keep", "weekly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("SMU-03", EX, "SMU-2400", "Electronics group", "working", "keep", "monthly", "booking", "iv-testing", 1,
      "standard", 60, 120, critical="no", weight=6, outlet="STRIP-05"),
    E("INC-01", EX, "Inc-150", PG, None, "new", "daily", "estimate", "sample-prep", 1, "standard", 250, 500,
      critical="yes", weight=60, notes="arriving: needs a spot"),
    # --- LAB-B ---
    E("HPLC-01", EX, "LC-100", AG, "working", "keep", "daily", "booking", "lc-ms", 1, "standard", 400, 600,
      critical="no", weight=60, outlet="STRIP-02"),
    E("MS-01", EX, "MS-Q", AG, "working", "keep", "daily", "booking", "lc-ms", 1, "standard", 1500, 2000,
      critical="yes", weight=110, outlet="STRIP-02", notes="must stay under vacuum"),
    E("PUMP-02", EX, "Rough-5", AG, "working", "keep", "daily", "estimate", "lc-ms", 1, "standard", 400, 800,
      critical="yes", weight=30, outlet="STRIP-02"),
    E("PC-02", EX, "Tower", AG, "working", "keep", "daily", "estimate", "lc-ms", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-02"),
    E("MON-02", EX, "24in", AG, "working", "keep", "daily", "estimate", "lc-ms", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-02"),
    E("EVAP-01", EX, "Evap-12", AG, "working", "keep", "weekly", "estimate", "lc-ms", 1, "standard", 300, 500,
      critical="no", weight=15),
    E("SONIC-01", EX, "Sonic-3", AG, "working", "keep", "weekly", "estimate", "lc-ms", 1, "standard", 100, 150,
      critical="no", weight=6, outlet="STRIP-03"),
    E("PRN-01", EX, "Inkjet", AG, "working", "keep", "weekly", "estimate", None, 1, "standard", 30, 60,
      critical="no", outlet="STRIP-03"),
    E("SRV-01", EX, "Server", AG, "working", "keep", "daily", "estimate", None, 1, "standard", 200, 400,
      critical="no", weight=15, outlet="OUT-10"),
    E("N2G-01", EX, "Gen-N2", AG, "working", "keep", "daily", "estimate", "lc-ms", 1, "standard", 600, 1200,
      critical="no", weight=70, outlet="OUT-10"),
    E("GC-01", EX, "GC-8", AG, "working", "keep", "weekly", "booking", "gc", 1, "standard", 800, 2000,
      critical="no", weight=50, outlet="OUT-11"),
    E("PC-03", EX, "Tower", AG, "working", "keep", "weekly", "estimate", "gc", 1, "standard", 120, 300,
      critical="no", weight=10, outlet="STRIP-04"),
    E("MON-03", EX, "24in", AG, "working", "keep", "weekly", "estimate", "gc", 1, "standard", 25, 40,
      critical="no", outlet="STRIP-04"),
    E("FTIR-01", EX, "IR-4", AG, "faulty", "undecided", "monthly", "booking", None, 1, "standard", 150, 250,
      critical="no", weight=35, outlet="OUT-11", notes="faulty: repair or replace?"),
    E("LAP-01", EX, "Laptop", AG, "working", "keep", "monthly", "estimate", None, 1, "standard", 50, 90,
      critical="no", outlet="STRIP-04"),
    E("LABEL-01", EX, "Label-P", AG, "working", "keep", "daily", "estimate", None, 1, "standard", 20, 40,
      critical="no"),
    E("CEN-02", EX, "Mini-12", AG, "working", "keep", "daily", "tally", "lc-ms", 1, "standard", 200, 400,
      critical="no", weight=6),
    E("VORT-02", EX, "Vortex", AG, "working", "keep", "daily", "estimate", "lc-ms", 1, "standard", 30, 60,
      critical="no", weight=2),
    E("BAL-02", EX, "Bal-220", AG, "working", "keep", "daily", "tally", "lc-ms", 1, "standard", 10, 20,
      critical="no", weight=8),
]
