"""Dropdown values for the lists sheet: name -> [(value, meaning)]."""

LISTS = {
    "category": [
        ("bench", "worktop / lab bench"), ("desk", "write-up or computer desk"),
        ("table", "free-standing table, balance table"), ("cabinet", "floor-standing cupboard"),
        ("shelf", "wall shelf or shelving unit"), ("drawer", "drawer (mount = in)"),
        ("pedestal", "drawer unit, often on castors"), ("container", "box, bin or tray holding items"),
        ("cart", "trolley"), ("instrument", "any instrument or device"),
        ("computer", "PC, controller"), ("monitor", "screen"),
        ("fridge", "fridge"), ("freezer", "-20, -80, LN2 dewar"),
        ("fume-hood", "fume hood, extraction or biosafety cabinet"), ("sink", "sink bowl, drainer"),
        ("gas-cylinder", "gas cylinder"), ("safety", "eyewash, shower, extinguisher, spill kit"),
        ("structure", "column, pipe boxing, radiator, electrical panel"), ("door", "door; clear_front = swing"),
        ("window", "mount = wall, z = sill height"), ("workspace", "working area that must stay clear"),
        ("overhead", "duct, beam, cable tray, light: mount = wall, z = underside"),
        ("other", ""),
    ],
    "mount": [
        ("floor", "stands on the room floor"), ("wall", "fixed to a wall; needs z"),
        ("on", "on top of parent"), ("under", "beneath parent; fits its free_under"),
        ("in", "inside parent: no position (drawer), or x/y inside a fume hood"), ("part", "piece of a group parent"),
    ],
    "faces": [("N", "front towards top of drawing"), ("NE", "diagonal, top-right"),
              ("E", "towards the right"), ("SE", "diagonal, bottom-right"),
              ("S", "towards the bottom (default)"), ("SW", "diagonal, bottom-left"),
              ("W", "towards the left"), ("NW", "diagonal, top-left")],
    "shape": [("rect", "w x d rectangle (default)"), ("circle", "w = diameter"),
              ("group", "composed of 'part' children")],
    "yesno": [("yes", ""), ("no", "")],
    "door": [("left", "hinged on your left as you face it"), ("right", "hinged on your right"),
             ("both", "double doors, hinged on both sides")],
    "level": [("problem", "something is wrong"), ("warning", "worth a look")],
    "condition": [("working", ""), ("faulty", "works, with problems"), ("broken", "doesn't work"), ("unknown", "")],
    "plan": [("keep", "stays"), ("relocate", "moves within or between rooms"), ("storage", "to a store room"),
             ("dispose", "to be decommissioned"), ("decommissioned", "gone: kept as a record"),
             ("new", "arriving, needs a spot"), ("undecided", "")],
    "usage": [("daily", ""), ("weekly", ""), ("monthly", ""), ("yearly", "a few times a year"),
              ("never", "not used in the last year")],
    "usage_source": [("tally", "tally sheet on the instrument"), ("booking", "booking system / logs"),
                     ("estimate", "someone's guess")],
    "plug_type": [("standard", "normal wall-socket plug"), ("C13", "IEC C13/C14 into a PDU or UPS"),
                  ("16A", "16 A industrial"), ("32A", "32 A industrial"), ("3-phase", "three-phase"),
                  ("hardwired", "no plug, wired in"), ("none", "no mains power")],
    "service_type": [("outlet", "wall or spine socket"), ("strip", "power strip / extension lead"),
                     ("gas", "gas tap"), ("vacuum", "vacuum tap"), ("air", "compressed air"),
                     ("water", "water tap"), ("drain", "drain"), ("network", "network port"),
                     ("exhaust", "extraction point / snorkel")],
    "item_category": [("tool", ""), ("consumable", ""), ("glassware", ""), ("spare-part", ""),
                      ("cable", ""), ("documentation", ""), ("other", "")],
    "backed": [("none", "mains only"), ("ups", "on a UPS"), ("generator", "emergency generator")],
    "phase": [(1, ""), (3, "")],
    "doc_type": [("coshh", "COSHH assessment"), ("risk-assessment", ""), ("calibration", "calibration certificate"),
                 ("electrical-test", "PAT / electrical safety test"), ("service", "service or maintenance record"),
                 ("other", "")],
    "doc_status": [("approved", ""), ("pending", "waiting for approval"), ("draft", ""), ("withdrawn", "")],
    "link_type": [("usb", 500), ("usb3", 300), ("ethernet", 10000), ("serial", 1500),
                  ("gpib", 200), ("video", 500), ("gas-line", ""), ("water-line", ""),
                  ("exhaust", ""), ("other", "")],
}

SECOND_HEADER = {"link_type": "default max_len, cm"}

PREFIXES = [
    ("BENCH", "bench / worktop"), ("DESK", "desk"), ("TBL", "table"), ("CAB", "cabinet"),
    ("SHELF", "shelf / shelving unit"), ("PED", "drawer pedestal"), ("BOX", "box, bin, tray"),
    ("CART", "cart / trolley"), ("FRG", "fridge"), ("FRZ", "freezer"), ("INC", "incubator"),
    ("HOOD", "fume hood / cabinet"), ("SINK", "sink"), ("PC", "computer"), ("MON", "monitor"),
    ("BAL", "balance"), ("CEN", "centrifuge"), ("SPEC", "spectrometer"), ("PUMP", "pump"),
    ("GAS", "gas cylinder"), ("EYE", "eyewash"), ("COL", "column"), ("PANEL", "electrical panel"),
    ("DOOR", "door"), ("WIN", "window"), ("WS", "workspace"),
    ("OUT", "outlet"), ("STRIP", "power strip"), ("NET", "network port"), ("GASTAP", "gas tap"),
    ("X.A  X.B", "parts of a composed object"), ("X.D1  X.D2", "drawers, numbered from the top"),
    ("X.S1  X.S2", "shelves, numbered from the top"), ("I-0001", "items: just number them"),
]
